# Generated by Django 5.1.2 on 2024-12-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kadi',
        ),
    ]
