# Generated by Django 5.1.2 on 2024-12-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_author_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
